### ISSUE TITLE
Recommend `pipx` to install offlinedatasci

### ISSUE THREAD

**Issue by abhidg** [carpentriesoffline/offlinedatasci#124]
Installing `pipx` (https://pipx.pypa.io) will be an additional step, but afterwards installing and updating offlinedatasci becomes simpler. Using `pipx` also ensures best practice such as installing binaries into a virtual environment.

**Alternatives**

* Keep using pip as now
* Give instructions to install offlinedatasci into a virtual environment

This should also bypass the long path error on Windows #119

**Comment by ethanwhite** [comment]
Is `pipx` appropriate since we also include a Python interface?

> pipx replaces a subset of pip's functionality; it lets you install cli applications but NOT libraries that you import in your code.

https://pipx.pypa.io/latest/comparisons/

Given this I don't think this can be the only or primary recommendation, but I'd be happy to add a second install description that will work but only if using the CLI.

Note that #119 has been solved so `pip` now works for all OSs.

**Comment by abhidg** [comment]
Yes, we should include both. I think most people will use the CLI, so probably pipx first, with pip if they want to use it as a library.

**Comment by ethanwhite** [comment]
Thanks! Just opened a PR and requested a review. I left `pip` first since it is the default and doesn't require installing a package that will be new to many folks, but I restructured things so that pipx is immediately after and states that we recommend it for CLI install.s
