### ISSUE TITLE
Installation is attempting to download old version of R

### ISSUE THREAD

**Issue by colinsauze** [carpentriesoffline/offlinedatasci#90]
Running "offlinedatasci install all ." using the latest download from the main branch in the Carpentries Offline installer I'm getting the following error: 

```
Warning: unable to access index for repository https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.0:
  cannot open URL 'https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.0/PACKAGES'
Error: Unable to retrieve available packages from CRAN
Execution halted
```

On the https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/ page the only versions available are 4.3 and 4.4.

**Comment by ethanwhite** [comment]
I'm looking at this but haven't been able to replicate it yet. Can you confirm that the `offlinedatasci` version is `0.3.0` (the current PyPI release)?

**Comment by ethanwhite** [comment]
I've tried this with the current PyPI release, the current main branch built locally, and the current main branch built with `pip3 install git+https://git@github.com/carpentriesoffline/offlinedatasci.git` which is what it looks like the installer is using and they all download 4.3.2 successfully. Ubuntu 22.04, Python 3.11 & 3.12.

**Comment by colinsauze** [comment]
I'm getting the following error during my builds on Ubuntu 22.04, but it still continues and everything else seems ok.

```
Warning: unable to access index for repository https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.1:
  cannot open URL 'https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.1/PACKAGES'
Error: Unable to retrieve available packages from CRAN
Execution halted

```

**Comment by ethanwhite** [comment]
OK, I finally understand this now. I think it's actually a bug, but it's a weird one that I didn't understand before.

`miniCRAN.R` is checking the local R version to determine which package versions to download. We're testing against the current release, so we don't see anything weird, but you're doing builds using the Debian R versions, which are older, and so are throwing errors because older versions of R don't support newer binary types on macOS.

This is a bug because for our main use case we need the R version to match the version of the installers that we're downloading, i.e., the newest version.
